development:
  adapter: postgresql
  encoding: unicode
  database: bateaux_development
  host: localhost
  port: 5432
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: bateaux_test
  host: localhost
  port: 5432
  pool: 5
  username: postgres
  password: postgres